### ISSUE TITLE
Comparison with cookiecutters ?

### ISSUE THREAD

**Issue by sideffect0** [arocks/edge#58]
https://github.com/pydanny/cookiecutter-django

**Comment by arocks** [comment]
Hi,

Cookie cutter is also a project starter but with a different philosophy. Edge uses the standard `django-admin` template parameter approach to customize your project as much as possible, while CookieCutter has a separate command which uses a Q&A interface to provide more customization. 

Cookie cutter offers plenty of starter templates and Edge offers just one. Hence we strive towards a more general starter template. If you have clearly known specialized needs then you might find a cookiecutter suited for you.

I would also add that Edge is more oriented towards a simpler set of requirements especially if you are starting out in development (for e.g. uses SQLlite rather than PostgreSQL). This is intended to make it more beginner-friendly.
